### ISSUE TITLE
Autoprefixer not working?

### ISSUE THREAD

**Issue by madeleineostoja** [giuseppeg/styled-jsx-plugin-postcss#15]
Trying to use autoprefixer over styled-jsx's built in prefixing (for grid shimming), but can't get it to work. All my other postcss plugins work a treat, but for whatever reason styled-jsx isn't picking up on Autoprefixer/isn't shimming grids. 

Using the same config with CSS modules in the same project, so I know that PostCSS itself is working fine. 

Ideas?

**Comment by JosephScript** [comment]
This should work now that it's been updated to use `postcss-preset-env`.

Here's a minimal example config:

```javascript
{
  "plugins": 
    "postcss-preset-env": {
      "browsers": ['ie 11'],
      "autoprefixer": { "grid": true }
    }
  }
}
```
Example input CSS:
```CSS
.grid {
  display: grid;
  grid-gap: 10px;
  grid-template:
    "a   b" 100px
    "c   d" 100px /
    1fr  1fr;
}

.cell-A {
  grid-area: a;
}

.cell-B {
  grid-area: b;
}

.cell-C {
  grid-area: c;
}

.cell-D {
  grid-area: d;
}
```

And then it turns into:
```CSS
.grid {
 display: -ms-grid;
 display: grid;
 grid-gap: 10px;
 -ms-grid-rows: 100px 10px 100px;
 -ms-grid-columns: 1fr 10px 1fr;
 grid-template:
   "a   b" 100px
   "c   d" 100px /
   1fr  1fr;
}

.cell-A {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.cell-B {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: b;
}

.cell-C {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: c;
}

.cell-D {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: d;
}
```

Please let me know if this works for you!
