### ISSUE TITLE
How to Ensure ES6 variables are resolved before parsing

### ISSUE THREAD

**Issue by khrome83** [giuseppeg/styled-jsx-plugin-postcss#3]
Right now it is not clear if ES6 string literals from closest scope will resolve before we parse the style content with PostCss.

For Example, introduced in 2.0, I should be able to use variables from closest scope:
```js
const Set = ({ children, mobile, tablet, desktop, gutter }) => ();
```

Here I am apply them we `mobile`, `tablet`, and `desktop`:
```css
      .set :global(.tile) {
        width: calc(100% / ${mobile});
        padding-bottom: var(--outer-padding-mobile);

        @media (--tablet-viewport) {
          width: calc(100% / ${tablet});
          padding-bottom: var(--outer-padding-tablet);
        }

        @media (--desktop-viewport) {
          width: calc(100% / ${desktop});
          padding-bottom: var(--outer-padding-desktop);
        }
      }
```

The result when running the JEST test is that I get a `%%styled-jsx-placeholder%%` which is not valid syntax and errors out. 

```console
 FAIL  __tests__/components/Set.test.js
  ● Test suite failed to run

    /Users/zane/GitHub/zanemilakovic.com/components/Set.js: Lexical error on line 1. Unrecognized text.
    100% / %%styled-jsx-placeho
    -------^

      at Parser.parseError (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:160:21)
      at Object.parseError (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:310:28)
      at Object.next (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:565:25)
      at Object.lex (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:575:22)
      at Object.lex (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:579:25)
      at lex (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:197:27)
      at Parser.parse (node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:210:26)
      at node_modules/postcss-calc/node_modules/reduce-css-calc/dist/index.js:35:30
      at walk (node_modules/postcss-value-parser/lib/walk.js:15:13)
      at ValueParser.walk (node_modules/postcss-value-parser/lib/index.js:18:5)


 RUNS  __tests__/components/P.test.js
Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1619.
```

**Comment by giuseppeg** [comment]
yea it is not easy, we need to make proper replace/restore functions. Unfortunately I don't have a lot of free time to invest on this - the plugin is just a proof of concept. I expect contribution to come from the community -> PR are welcome!

**Comment by khrome83** [comment]
@giuseppeg - can you give me some more info on where the change should take place. Should Styled-JSX process the variables before sending to plugin, or should the plugin not throw a error for this, treat it as "valid" and then send the results back?

Additionally, I tried to remove the nested-calc function - 

```css
      .set :global(.tile) {
        width: ${100 / mobile}%);
        padding-bottom: var(--outer-padding-mobile);

        @media (--tablet-viewport) {
          width: ${100 / tablet}%);
          padding-bottom: var(--outer-padding-tablet);
        }

        @media (--desktop-viewport) {
          width: ${100 / desktop}%);
          padding-bottom: var(--outer-padding-desktop);
        }
      }
```

The results were that it removed the error, but made it so the output from the Styled JSX processing stripped out both `width` and `padding-bottom` from the `.set :global(.tile)` selector.

Here is the output - 

```css
.set.jsx-402683664 {
  display: -webkit-box;
  display: -ms-flexbox;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  padding-top: 5vw;
}

@media (min-width:48rem) {
  .set.jsx-402683664 {
    padding-top: 4vw;
  }
}

@media (min-width:62rem) {
  .set.jsx-402683664 {
    padding-top: 2.5vw;
  }
}

@media (min-width:48rem) {}

@media (min-width:62rem) {}

.gutter.jsx-402683664 .tile {
  margin: 0 2.5vw;
}

@media (min-width:48rem) {
  .gutter.jsx-402683664 .tile {
    margin: 0 2vw;
  }
}

@media (min-width:62rem) {
  .gutter.jsx-402683664 .tile {
    margin: 0 1.25vw;
  }
}
```
